twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%env(TEMPLATE_NAME)%': theme
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
